using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Project1
{
    /// <summary>
    /// This class manages the overall state of the game, including the maze layout, player status, score, items, and enemies.
    /// </summary>
    public class GameState
    {
        /// <summary>
        /// Sets the maze layout using a 2D array of CellType enums which was generated by the Maze class.
        /// Sets score, game over status, exit position, messages, player, items, and enemies.
        /// </summary>
        public Maze.CellType[,] Maze { get; private set; }
        public int Score { get; set; }
        public bool IsGameOver { get; set; }
        public int ExitX { get; set; }
        public int ExitY { get; set; }
        public string Message { get; set; }
        public Player Player { get; private set; }
        public List<Item> Items { get; private set; }
        public List<Monster> Enemies { get; private set; }

        /// <summary>
        /// Sets the initial game state with the provided maze layout and initializes other properties.
        /// </summary>
        /// <param name="maze"></param>
        public GameState(Maze.CellType[,] maze) 
        {
            Maze = maze;
            Items = new List<Item>();
            Enemies = new List<Monster>();
            Score = 0;
            IsGameOver = false;
            Message = "";
        }

        /// <summary>
        /// Adds points to the current score.
        /// </summary>
        /// <param name="points"></param>
        public void AddScore(int points)
        {
            Score += points;
        }

        /// <summary>
        /// Ends the game by setting IsGameOver to true.
        /// </summary>
        public void EndGame()
        {
            IsGameOver = true;
        }

        /// <summary>
        /// Sets the exit position in the maze.
        /// </summary>
        /// <param name="x"></param>
        /// <param name="y"></param>
        public void SetExit(int x, int y)
        {
            ExitX = x;
            ExitY = y;
        }

        /// <summary>
        /// Sets the Player object representing the player to be used in the game.
        /// </summary>
        /// <param name="player"></param>
        public void SetPlayer(Player player)
        {
            Player = player;
        }


        /// <summary>
        /// Adds an item to the list of items in the game to be placed in the maze.
        /// </summary>
        /// <param name="item"></param>
        public void AddItem(Item item)
        {
            Items.Add(item);
        }

        /// <summary>
        /// Adds a monster to the list of enemies in the game to be placed in the maze.
        /// </summary>
        /// <param name="enemy"></param>
        public void AddMonster(Monster enemy)
        {
            Enemies.Add(enemy);
        }
    }
}
